const newData = {
    drinks: [
        {
            name: 'Dark & Stormy',
            id: '1',
            image: 'dark_and_stormy.jpg',
            ingredients: ['rum','ginger beer', 'lime juice'],
            directions: 'Fill a tall glass with ice cubes. Add rum, then pour in ginger beer and lime juice. Stir with a barspoon. Garnish with a lime wedge.',
            rating: '9',
            description: 'Sweet and sharp, the Dark and Stormy climbed out of the Bermuda Triangle to become one the most popular Caribbean rum cocktails you can make.',
        },
        {
            name: 'French 75',
            id: '2',
            image: 'french_75.jpg',
            ingredients: ['london dry gin','superfine sugar', 'lemon juice', 'brut champagne'],
            directions: 'Shake gin, sugar, and lemon juice well with cracked ice in a chilled cocktail shaker. Strain into a Collins glass half-full of cracked ice. Top off with champagne.',
            rating: '10',
            description: 'It looks like bubbly effervescence, but looks deceive. The French 75, with gin and champagne, packs a wallop, made all the more dangerous by how delightful it is to drink.',
        },
        {
            name: 'Boulevardier',
            id: '3',
            image: 'boulevardier.jpg',
            ingredients: ['bourbon','campari', 'sweet vermouth'],
            directions: 'Stir ingredients with ice in a mixing glass until chilled. Strain into a coupe glass. Garnish with an orange twist.',
            rating: '9',
            description: 'The Negroni\'s wintery counterpart is the Boulevardier, a whiskey cocktail invented for expat Americans bumming around Paris in the early 20th century.',
        },
        {
            name: 'Bloody Mary',
            id: '4',
            image: 'bloody_mary.jpg',
            ingredients: ['tomato juice','horseradish', 'worchestershire sauce', 'celery seeds', 'hot sauce', 'lemon juice', 'lime juice', 'salt', 'pepper', 'vodka'],
            directions: 'Blend tomato juice, horseradish, Worcestershire, and celery seeds until smooth. Add hot sauce, lemon juice, lime juice, salt, and pepper, then blend. Adjust the mix depending on how spicy, salty, or citrusy you like it. Add 1 tbsp. vodka to stabilize the mix and keep the juices fresh, then blend. Combine 6-8 oz. of the mix with 2 oz. of vodka into a glass with ice. Pour back and forth into another glass 3 or 4 times to mix, then garnish however you like.',
            rating: '8',
            description: 'Oh yeah, you can and should make your own Bloody Mary mix. It\'s labor intensive, sure, but it\'s highly customizable. You can decide just how you want the horseradish to play off the citrus that plays off the hot sauce heat.',
        },
        {
            name: 'Gimlet',
            id: '5',
            image: 'gimlet.jpg',
            ingredients: ['london dry gin','lime juice'],
            directions: 'Shake ingredients in a cocktail shaker with cracked ice. Strain into a chilled cocktail glass, and garnish with a lime.',
            rating: '9',
            description: 'Rose\'s lime cordial is perfectly balanced by herbaceous dry gin in this tart, impossible-to-screw-up British cocktail.',
        },
        {
            name: 'Moscow Mule',
            id: '6',
            image: 'moscow_mule.jpg',
            ingredients: ['vodka','ginger beer', 'lime juice'],
            directions: 'Squeeze lime juice into a Moscow Mule mug, then drop in spent shell. Add 2-3 ice cubes and vodka, then fill with ginger beer.',
            rating: '8',
            description: 'This cocktail is crisp and cooling, and good for any season. Plus it (usually) comes in a copper mug, which is neat.',
        },
        {
            name: 'Aperol Spritz',
            id: '7',
            image: 'aperol_spritz.jpg',
            ingredients: ['aperol','prosecco', 'club soda', 'orange slices'],
            directions: 'Build Aperol, prosecco, and club soda in a wine glass over ice. Garnish with fresh orange slices in the glass.',
            rating: '7',
            description: 'For daytime drinking, you really can\'t beat an Aperol Spritz. It\'s pretty basic, but then again, that\'s its charm. Just ask all the bar patrons crowding the patio around you, Spritzes in hand.',
        },
        {
            name: 'Mojito',
            id: '8',
            image: 'mojito.jpg',
            ingredients: ['white rum','lime juice', 'superfine sugar', 'mint leaves', ['club soda' || 'seltzer']],
            directions: 'In a smallish Collins glass, muddle lime juice with 1/2 to 1 tsp. superfine sugar. Add the mint leaves, mushing them against the side of the glass, then fill the glass 2/3 with cracked ice and pour in the rum. Pitch in the squeezed-out lime shell and top off with club soda or seltzer.',
            rating: '9',
            description: 'Really, it\'s difficult to imagine a combination more refreshing than rum, lime, mint, and bubbles. We have Cuba to thank, and thank heartily, for the Mojito.',
        },
        {
            name: 'Manhattan',
            id: '9',
            image: 'manhattan.jpg',
            ingredients: ['rye whiskey', 'italian vermouth', 'angostura bitters'],
            directions: 'Stir ingredients well with cracked ice, then strain into a chilled cocktail glass. Garnish with a twist or maraschino cherry.',
            rating: '9',
            description: 'A Manhattan is strong in all ways. The flavor is deep and unabashed, and the ABV is nothing to scoff at. It\'s a cocktail stalwart, and not for the weak of heart.',
        },
        {
            name: 'Margarita',
            id: '10',
            image: 'margarita.jpg',
            ingredients: ['silver tequila','cointreau', 'lime juice', 'salt'],
            directions: 'Rub the rim of a chilled cocktail glass with lime juice and dip in coarse salt. Shake tequila, Cointreau, lime juice, and ice in a mixing glass, then strain into the salted glass over ice.',
            rating: '9',
            description: 'The Margarita is the workhorse of summer. It\'s best made with Cointreau, and if you like it a little sweeter, agave syrup is a killer addition.',
        },
        {
            name: 'Whickey Sour',
            id: '11',
            image: 'whiskey_sour.jpg',
            ingredients: [['bourbon' || 'rye'],'lemon juice', 'superfine sugar', 'egg white'],
            directions: 'Shake ingredients well with cracked ice, strain into a chilled cocktail glass, and garnish with a lemon wedge and/or maraschino cherry.',
            rating: '9',
            description: 'For those nights when you want to cleanse your palate, opt for a puckery Whiskey Sour. Bourbon is traditional, but rye can lend it some punch.',
        },
        {
            name: 'Dry Martini',
            id: '12',
            image: 'dry_martini.jpg',
            ingredients: ['dry vermouth','gin', 'olives'],
            directions: 'Fill a metal shaker with cracked ice. Pour in the dry vermouth, stir briefly, and strain out (this may be discarded). Add gin, then stir briskly for about 10 seconds. Strain into a chilled cocktail glass, and garnish with olives or a lemon twist.',
            rating: '9',
            description: 'A classic martini technically should be made with gin and served bone-chillingly cold. Order it stirred, not shaken. Sorry, 007.',
        },
        {
            name: 'Daiquiri',
            id: '13',
            image: 'daiquiri.jpg',
            ingredients: ['white rum','lime juice', 'superfine sugar'],
            directions: 'Squeeze lime into a shaker, stir in sugar, then add rum. Shake well with cracked ice and strain into a chilled cocktail glass.',
            rating: '6',
            description: 'A citrusy marriage of rum and lime in the Caribbean gave us the simple but satisfying Daiquiri. Strain it and serve it sans ice.',
        },
        {
            name: 'Negroni',
            id: '14',
            image: 'negroni.jpg',
            ingredients: ['london dry gin','campari', 'vermouth'],
            directions: 'Add the ingredients together in a cocktail shaker. Stir well with cracked ice. Strain into a glass over cubed ice, then garnish with a twist of orange peel.',
            rating: '9',
            description: 'The Negroni is the epitome of refined summer drinking: sweet and bitter and invigorating.',
        },
        {
            name: 'Old Fashioned',
            id: '15',
            image: 'old_fashioned.jpg',
            ingredients: [['bourbon' || 'rye whiskey'],'angostura bitters', 'sugar cube', 'club soda'],
            directions: 'Place sugar in an Old Fashioned glass. Wet it down with Angostura bitters and a splash of club soda, then muddle. Add a large ice cube and whiskey. Stir, then garnish with an orange twist.',
            rating: '9',
            description: 'The Old Fashioned is as classic as they come—the original whiskey cocktail. Even in the two centuries since its inception, it\'s still the most respected cocktail in the world, and not the least bit musty for its age. Rye will make it spicier than bourbon.',
        },
        {
            name: 'Mimosa',
            id: '16',
            image: 'mimosa.jpg',
            ingredients:['champagne', 'orange juice'],
            directions: 'Pour Champagne in Champagne flute, Add orange juice, Garnish with orange slice',
            rating: '9',
            description: 'The mimosa is the 4th most popular cocktail in the U.S. It\'s, unsurprisingly, most popular during the morning and afternoon. It\'s said that a bartender at the Ritz in Paris invented the mimosa in 1925. It\'s also said that it was invented around the turn of the 20th century in the Mediterranean. Though, that\'s maybe doing some disservice to the Spaniards who have been drinking orange juice and sparkling wine for centuries. Who can really say where these things come from? It gets its name from the yellow-flowering mimosa plant. That we do know. If you have a brunch service, expect to go through many wine bottle sizes or cases of wine on this cocktail.',
        },
        {
            name: 'Cosmopolitan',
            id: '17',
            image: 'cosmopolitan.jpg',
            ingredients:['vodka', 'cranberry juice', 'cointreau', 'lime juice'],
            directions: '    Pour vodka, cranberry juice, Cointreau, and lime juice into a shaker with ice cubes, shake, Strain into cocktail glass, Garnish with lime or lemon wheel',
            rating: '9',
            description: 'The cosmopolitan is credited to Toby Cecchini of Manhattan\'s The Odeon restaurant in 1987. In the grand scheme of cocktails, the cosmo is young. There is a similar recipe from the 1930s that calls for gin, Cointreau, lemon juice, and raspberry syrup. Like most cocktails, there are multiple sources claiming multiple creation stories. What we do know is that it gained popularity like mad in the 1990s on the back of Carrie Bradshaw and now single-handedly represents a certain type of social sophistication.',
        },
        {
            name: 'White Russian',
            id: '18',
            image: 'white_russian.jpg',
            ingredients:['coffe liquor', 'vodka', 'cream'],
            directions: 'Add ice to rocks or old-fashioned glass, Add coffee liqueur and vodka, Top off with cream, Tell them "the dude" sent you',
            rating: '9',
            description: 'The White Russian is a Black Russian with cream added. They have nothing to do with Russia besides their use of vodka. And vodka was created in Poland. Just one of those things, I guess. A Belgian named Gustave Tops invented the cocktail in 1949 in honor of the U.S. ambassador to Luxembourg\'s visit to Brussels. We\'ve now mentioned five countries in the last few sentences. You can be forgiven if you think the origin story of the White Russian doesn\'t follow a logical narrative thread.',
        },
        {
            name: 'Gin Fizz',
            id: '19',
            image: 'gin_fizz.jpg',
            ingredients:['gin', 'lemon juice', 'simple syrup', 'club soda'],
            directions: 'Pour all ingredients in a shaker with ice cubes, shake, Strain into an 8 oz. glass with no ice in it, Top with club soda, Garnish with lemon wedge or twist',
            rating: '9',
            description: 'The defining feature of a fizz, which is a family of cocktails, is the combination of acidic juice and fizzy water. Created in New Orleans around the 1870s, the drink became popular in the U.S. in the first half of the 20th century. It got so popular, in fact, that bars needed to hire entire teams of bartenders to take shifts making the darn things. And then around 1950, the domestic U.S. popularity couldn\'t contain itself. The drink went international. The rest is history. Folks usually put gin, whiskey, and in fizzes, but gin is the most popular. It\'s certainly one of our favorite classic cocktails.',
        },
        {
            name: 'Aqua Velvet',
            id: '20',
            image: 'aqua_velvet.jpg',
            ingredients:['vodka', 'gin', 'blue curacao', 'simple syrup', 'lemon juice', 'lemon wedge'],
            directions: 'Pour all ingredients into a glass, adding the soda water last (or sparkling lemonade). Garnish and serve. Pitcher variation: Add 1 cup vodka, 1 cup gin, ¾ cup blue curacao to a pitcher. Top off with 4 cups sparkling lemonade (or 1 cup simple syrup, 1 cup fresh lemon juice and 2 cups soda water). Serve over ice.',
            rating: '9',
            description: 'A drink inspired by aftershave? Yes, that\'s this bubbly bright blue masterpiece: the Aqua Velva! A child of the 1980\'s, it\'s got a searing neon color that belies its birth. While some versions of this cocktail can be sickly sweet, make it with fresh lemon juice and soda water and it\'s a refreshingly complex. The botanical notes in the gin shine though, pairing perfectly with the citrus of the blue curacao. It even tastes a teeny bit like… deliciously drinkable aftershave.',
        },
        {
            name: 'Aviation',
            id: '21',
            image: 'aviation.jpg',
            ingredients:['gin', 'lemon juice', 'maraschino liqueur', 'creme de violette','cherries'],
            directions: 'Add the gin, lemon juice, maraschino liqueur, and creme de violette to a cocktail shaker. Fill it with ice and shake it until cold. Strain into a cocktail glass. Garnish with a Luxardo cherry, if desired.',
            rating: '9',
            description: 'Here\'s a classic cocktail that\'s come back en vogue: the Aviation! This purple cocktail tastes as great as it looks: it\'s sweet tart, with a hint of cherry and a floral nuance that come from maraschino liqueur and creme de violette! To be honest, Alex and I had avoided this drink for quite a while because of the unique specialty ingredients. But that first sip was so intriguing that we immediately agreed: they\'re worth the purchase. It\'s a great drink for the adventurous home mixologist who doesn\'t mind adding another liqueur or two to their collection. Here\'s how to make it!',
        },
        {
            name: 'Basil Collins',
            id: '22',
            image: 'basil_collins.jpg',
            ingredients:['basil', 'cucumber', 'gin', 'simple syrup', 'lemon juice', 'soda water'],
            directions: 'In a cocktail shaker, muddle the basil leaves. Add the cucumber slices and muddle again.Add the gin, simple syrup, and lemon juice and fill the shaker with ice. Shake for 15 seconds until cold. Strain the drink into an ice-filled highball glass. Top with soda water and garnish with additional cucumber slices and basil.',
            rating: '9',
            description: 'Here\'s a deliciously bubbly drink that\'s calling your name (and ours too): the Basil Collins! This basil cocktail is a summer spin on the Tom Collins, featuring cucumber and that peppery fresh herb you might be growing in a pot or your garden. It\'s got a tangy sweet flavor, a cucumber basil essence and a load of bubbles packed in that glass. Add some jingling ice cubes, and it\'s a drink fit for flip flops and summer evenings.',
        },
        {
            name: 'Bees Knees',
            id: '23',
            image: 'bees_knees.jpg',
            ingredients:['gin', 'honey', 'simple syrup', 'lemon juice'],
            directions: 'Add the gin, lemon juice, and mix honey and simple syrup to a cocktail shaker. Fill with a handful of ice and shake until very cold. Strain the drink into a cocktail glass. Garnish with a lemon twist.',
            rating: '9',
            description: 'Here\'s a classy classic cocktail that\'s refreshing and sweet tart: the Bees Knees! It\'s got a cute 1920\'s name and a smooth flavor to match. The unique element? Honey syrup. Making simple syrup with honey instead of refined sugar adds a rich depth to cocktails. Combine it with lemon and gin, and you\'ve got a refreshing cocktail that goes down easy. Naturally sweet and perfectly balanced, it\'s easy to make too! Here\'s what you need to know.',
        },
        {
            name: 'Bijou',
            id: '24',
            image: 'bijou.jpg',
            ingredients:['gin', 'sweet vermouth', 'chartreuse', 'orange bitters', 'lemon peel'],
            directions: 'Combine the gin,sweet vermouth, Chartreuse and bitters in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Strain the drink into a cocktail glass. Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'Looking for a unique classic cocktail to impress? Try the Bijou cocktail! This drink is named for the colors of glittering jewels of the three liquors that make it up. It\'s been around for over a century, with a spirit-forward flavor that\'s crisp and herbaceous. Take one sip and you\'ll be reminded of a Manhattan. But it\'s even more interesting, with an herbal undertone to the finish. This one is full of surprises: and all your guests will be impressed. Here\'s how to make the Bijou!',
        },
        {
            name: 'Blood Orange Gin & Tonic',
            id: '25',
            image: 'blood_orange_gin_and_tonic.jpg',
            ingredients:['gin', 'blood orange juice', 'tonic water', 'mint'],
            directions: 'Add gin, blood orange juice, and ice and stir. Pour the tonic water onto a bar spoon into the glass (to increase the bubbles). Stir once. Add the garnishes and serve.',
            rating: '9',
            description: 'Here\'s arguably the easiest blood orange cocktail out there: the Blood Orange Gin and Tonic! There\'s nothing better than a cocktail you can mix up right in the glass, right? Much as we love a good blood orange margarita or blood orange martini…this one\'s even easier to make. Here the botanicals from the gin mesh perfectly with the bright citrus of the blood orange. It makes for a sunny twist on your favorite G&T! Here\'s how to make it!',
        },
        {
            name: 'Bramble',
            id: '26',
            image: 'bramble.jpg',
            ingredients:['gin', 'lemon juice', 'simple syrup','creme de mure', 'lemon slice', 'blackberry'],
            directions: 'Add crushed ice to a lowball glass. Add the gin, lemon juice and simple syrup to a cocktail shaker. Fill it with ice and shake until cold. Strain the drink into the glass with crushed ice. Drizzle the creme de mure over crushed ice. Garnish with a lemon slice and afresh blackberry.',
            rating: '9',
            description: 'Here\'s a special cocktail that solidified itself as a new favorite at first sip: the Bramble cocktail! This drink has the sweetest name and it\'s full of tangy, fruity and sophisticated flavors. This refreshing drink uses a special blackberry liqueur called crème de mûre. It might not be on hand in your liquor cabinet, but it should be: one swig is like a bite of fruity blackberry candy! This drink is one of the great modern classic gin cocktails…and to us, it\'s near perfection in a glass.',
        },
        {
            name: 'Clover Club',
            id: '27',
            image: 'clover_club.jpg',
            ingredients:['gin', 'grenadine syrup', 'lemon juice', 'egg white', 'raspberry', 'lemon twist'],
            directions: 'Add the gin, raspberry syrup or grenadine, lemon juice, and egg white to a cocktail shaker without ice. Shake for 15 seconds. Add the ice to the cocktail shaker. Shake again for 30 seconds. Strain the drink into a cocktail glass; the foam will collect at the top. Garnish with a lemon twist or fresh raspberries.',
            rating: '9',
            description: 'Here\'s a sophisticated classic cocktail that steals the show: the Clover Club! This bright pink drink stems back before Prohibition, but it\'s just as en vogue today. Sweet raspberry or grenadine syrup combine with zingy lemon and gin to make a perfectly balanced sweet tart drink. The best part: a classic egg white foam gives a creamy body and frothy texture to each sip! This one\'s a unique gin cocktail that\'s just plain fun. We often make gin cocktails like the Gin Fizz: the one\'s a colorful variation on the theme.',
        },
        {
            name: 'Corpse Reviver No. 2',
            id: '28',
            image: '.jpg',
            ingredients:['gin', 'lemon juice', 'cointreau', 'dry vermouth', 'absinthe', 'orange peel'],
            directions: 'Add the gin, lemon juice, Cointreau, dry vermouth, and absinthe to a cocktail shaker. Fill it with ice and shake it until cold. Strain into a cocktail glass. If desired, garnish with an orange peel or orange wedge. ',
            rating: '9',
            description: 'Here\'s a classic cocktail that\'s as unique as its name…the Corpse Reviver No 2! To be honest, we were a little wary of this cocktail at first because of its moniker. But it turns out that the Corpse Reviver has nothing scary or ghoulish about it. In fact, it\'s damn good. It\'s a classic gin sour cocktail that\'s tart and zingy from lemon juice and orange liqueur, with a hint of licorice on the finish. It\'s truly a stunner…and the name will impress all your friends. Let\'s get mixing!',
        },
        {
            name: 'Cynar Negroni',
            id: '29',
            image: 'cynar_negroni.jpg',
            ingredients:['gin', 'vermouth', 'cynar', 'lemon peel'],
            directions: 'Combine the gin, sweet vermouth, and Cynar in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Add ice to a lowball glass, and strain the drink into the glass. Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'When it comes to Negroni variations, we tend to like them even better than the original. Such is the case with the Cynar Negroni! This intriguing spin features Cynar, an Italian amaro with hints of caramel, toffee and an herbal bitter finish. It makes a bitter, mellow Negroni that\'s more interesting to drink, in our opinion! Here\'s how to make it, and a few notes about this unique liqueur.',
        },
        {
            name: 'Dirty Martini',
            id: '30',
            image: 'dirty_martini.jpg',
            ingredients:['gin', 'dry vermouth', 'olive juice', 'olive'],
            directions: 'Combine the gin, vermouth, and olive juice in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds until very cold. Strain the drink into a cocktail or martini glass (purists chill the glass first). Garnish with an olive.',
            rating: '9',
            description: 'The martini is one of the most iconic cocktails of all time. The classic martini is just two ingredients: crisp, cool, and spirit-forward. But how to make it even more perfect? The Dirty Martini! Add a splash of olive juice to your martini, and the way it rounds out the flavor is true perfection. It\'s tangy, salty, briny and complex. The martini is seeped in tradition, and as you might expect: we have our own opinion on how to make it perfectly. Here\'s how to make a classic Dirty Martini…the best way.',
        },
        {
            name: 'Gibson',
            id: '31',
            image: 'gibson.jpg',
            ingredients:['gin', 'dry vermouth', 'cocktail onions'],
            directions: 'Combine the gin and vermouth in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds until very cold. Strain the drink into a cocktail or martini glass (purists chill the glass first). Garnish with cocktail onions.',
            rating: '9',
            description: 'Calling all martini lovers! Have you met the Gibson cocktail? This classic gin drink is essentially a martini with an onion garnish. This switch up on the classic “lemon or olive” garnish brings a savory element that makes it an altogether new drink. The Gibson is crisp, cool, searing, and spirit-forward, punctuated by the pungent onion garnish. Move over, Classic Martini: there\'s a new drink in town.',
        },
        {
            name: 'Gin & Coke',
            id: '32',
            image: 'gin_and_coke.jpg',
            ingredients:['gin', 'cola','lime juice', 'angostura bitters'],
            directions: 'Add the gin and ice to a glass and stir to combine. Top with the cola. Squeeze in the juice from the lime wedge (or ½ ounce lime juice) and serve. Garnish with additional lime wedges or wheels. ',
            rating: '9',
            description: 'Looking for an easy gin cocktail that tastes better than the sum of its parts? Try the Gin and Coke! Sure, the Gin and Tonic is probably the first easy gin drink that jumps to mind. But mixing this botanical liquor with cola is a very good idea. Use the right ratio and the delicate flavor of gin shines through without getting overpowered by the sweet cola. Add a zing of lime and it tastes totally novel. Move over, rum and coke. Gin\'s got the spotlight!',
        },
        {
            name: 'Gin & Lemonade',
            id: '33',
            image: 'gin_and_lemonade.jpg',
            ingredients:['gin', 'lemonade', 'mint', 'lemon slice'],
            directions: 'In a glass, pour in the lemonade and gin. Add ice and garnish with fresh mint and lemon slices.',
            rating: '9',
            description: 'Need an easy 2 ingredient cocktail idea with gin? Try this Gin and Lemonade! It might sound overly simple, but gin and lemon are a natural cocktail pairing featured in many classic drinks. What do the Tom Collins, Gin Fizz, and French 75 have in common? They all pair gin and lemon! If you\'re in the mood for a laid back version of these drinks, simply stir together gin and lemonade.',
        },
        {
            name: 'Gin & Soda',
            id: '34',
            image: 'gin_and_soda.jpg',
            ingredients:['gin', 'soda water', 'lime wedge'],
            directions: 'Add the gin, and ice to the glass and stir gently. Top with the soda water and a squeeze of lime juice. Serve immediately.',
            rating: '9',
            description: 'Looking for a fast and easy gin cocktail? Try Gin and Soda! Adding club soda to gin lets you enjoy the botanical intrigue of the flavor: and it takes no time at all to mix up. This cocktail is no new idea: it\'s very similar to the Gin Rickey, a classic drink from the 1880\'s. It\'s a refreshing drink that just so happens to be low calorie, too.',
        },
        {
            name: 'Gin & Tonic',
            id: '35',
            image: 'gin_and_tonic.jpg',
            ingredients:['gin', 'tonic water'],
            directions: 'Add lots of ice to a large cocktail or wine glass and stir to chill the glass. Drain any melted water.Pour in the gin. Add the garnishes. Pour the tonic water onto a bar spoon into the glass (to increase the bubbles). Stir once and serve.',
            rating: '9',
            description: 'What\'s more refreshing than a gin and tonic? Its crisp, botanical flavor is straightforward but at the same time intriguing: a feat using only 2 ingredients! It\'s no wonder that this is one of the world\'s popular cocktails. We\'ve researched to gather a few tips about making the perfect gin and tonic. Keep reading for our secrets.',
        },
        {
            name: 'Gin Fizz',
            id: '36',
            image: 'gin-fizz.jpg',
            ingredients:['gin', 'lemon syrup', 'simple syrup', 'egg white', 'lemon twist'],
            directions: 'Place the gin, lemon juice, syrup and egg white in a cocktail shaker. Shake vigorously for 15 seconds. Fill the shaker with ice and shake for 30 seconds until cold. Strain the drink into a glass and top with the soda water; the egg white foam forms on top. If desired, garnish with a lemon twist. Serve immediately.',
            rating: '9',
            description: 'Ever had a Gin Fizz? It\'s one of the best uses of a bottle of gin around (really). This classic cocktail from the 1870\'s is perfectly balanced, both sweet and tart with a pop of lemon and a botanical finish. Add to that a frothy egg white foam topping, which adds the best creamy texture to each sip. Oh and it takes only 5 minutes to make! Ready to experience this iconic gin cocktail?',
        },
        {
            name: 'Gin Gimlet',
            id: '37',
            image: 'gin_gimlet.jpg',
            ingredients:['gin', 'lime juice', 'simple syrup', 'soda water'],
            directions: 'Add gin, lime juice, and syrup to a cocktail shaker. Fill with ice and shake until cold. Strain into glass and top with a splash of soda water, if desired. Garnish with a lime wheel and serve.',
            rating: '9',
            description: 'Here\'s a classic cocktail that is super refreshing and takes only 5 minutes to whip up: the gimlet! Not only is the gimlet simple to make, it\'s the perfect balance of sweet and tart with the botanical flavor of gin. Alex and I got our hands on a bottle of local gin and have been mixing up all sorts of gin cocktails: a classic Gin and Tonic, Watermelon Gin Cocktails, a Hanky Panky, and the Gin Fizz. For our latest gin drink we decided to go retro and go with a gin gimlet cocktail: and it was even better than expected.',
        },
        {
            name: 'Gin & Basil',
            id: '38',
            image: 'gin_and_basil.jpg',
            ingredients:['basil leaf', 'gin', 'lime juice', 'lemon juice', 'simple syrup'],
            directions: 'Add the basil leaves to a cocktail shaker and gently muddle 4 to 5 times until the oil is released, but the basil is not broken. Add the remaining ingredients to the cocktail shaker. Fill it with ice and shake until cold. Strain the drink into a glass. Garnish with a fresh basil leaf.',
            rating: '9',
            description: 'Love fresh basil? Us too. Here\'s our new favorite way to use it: this Basil Cocktail! The peppery green herb adds a beautifully fresh flavor to this drink. It\'s a lemon lime gin drink: crisp and cool, with a sweet tart flavor. When Alex handed it to me and I took the first sip, I was sold. There\'s nothing better than basil in the summer, and we think this is just the way to use it. (Or a Basil Gimlet.) Here\'s how to use basil in cocktails, and the recipe for this lovely green drink.',
        },
        {
            name: 'Gin Basil Smash',
            id: '39',
            image: 'gin_basil_smash.jpg',
            ingredients:['basi leaf', 'gin', 'lemon juice0', 'simple syrup'],
            directions: 'Place the basil leaves in a cocktail shaker and muddle them (gently mash). Add the gin, lemon juice and simple syrup to the cocktail shaker. Add 2 handfuls ice and shake until cold. Strain the drink into an ice-filled lowball glass. If desired, top with splash of soda water. Garnish with additional basil leaves.',
            rating: '9',
            description: 'Got basil? Love gin? Here\'s the ideal drink for you: the Gin Basil Smash! This modern spin on the Whiskey Smash is light and herbaceous, pairing peppery basil with botanical gin. If there\'s summer in a cocktail glass, this is it! We love drinking our herbs all season long, and this new addition to our summer cocktails perfectly captures that feeling of fresh cut grass between your toes and sticky melted popsicle fingers. (At least, we think so!)',
        },
        {
            name: 'Gin Gin Mule',
            id: '40',
            image: 'gin_gin_mule.jpg',
            ingredients:['mint', 'lime juice', 'gin', 'ginger beer', 'lime wedge'],
            directions: 'Gently muddle (mash) the mint sprigs in the bottom of the mug using a cocktail muddler or wooden spoon. Add the lime juice, simple syrup and gin. Stir to combine. Add ice and the ginger beer and stir gently. Garnish with lime and mint',
            rating: '9',
            description: 'It\'s minty, it\'s bubbly, it\'s refreshing: meet the Gin Gin Mule! You might think it\'s a just liquor swap in a mule, but this cocktail is more than meets the eye! Considered a modern classic cocktail, it\'s a mashup of the Moscow mule and minty Mojito. You\'ve got the bubbly ginger beer and lime of a mule, balanced by the muddled mint and sweetness of a mojito. The Gin Gin Mule results in a much more balanced drink than it\'s classic counterpart. It\'s become a big favorite around here! Here we\'ll show you how to make this signature drink and a Moscow mule with gin.',
        },
        {
            name: 'Gin Rickey',
            id: '41',
            image: 'gin_rickey.jpg',
            ingredients:['gin', 'lime juice', 'soda water', 'lime wedge'],
            directions: 'Add the gin and lime juice to highball glass and stir. Fill with ice and top with sparkling water. Garnish with a lime wedge.',
            rating: '9',
            description: 'It\'s tall, it\'s bubbly, and it\'s one of the easiest to make cocktails out there. Try the Gin Rickey! This classic cocktail was born in the 1880s and has been popular ever since. And for good reason: it\'s tangy, bubbly, and irresistibly delicious. If you love a Vodka Soda or a Gin and Tonic: this is the drink for you! There\'s no frills: just a classy classic highball. Alex and I love sipping on these afternoons on the patio — along with the rickey\'s many variations. Here\'s how to make it!',
        },
        {
            name: 'Gin Sour',
            id: '42',
            image: 'gin_sour.jpg',
            ingredients:['gin', 'lemon juice', 'egg white', 'simople syrup', 'angostura bitters'],
            directions: 'Add the gin, lemon juice, syrup, and egg white to a cocktail shaker without ice. Shake for 15 seconds. Add the ice to the cocktail shaker. Shake again for 30 seconds. Strain the drink into a glass; the foam will collect at the top. Serve with or without ice. Garnish with bitters swirled into foam and lemon twist.',
            rating: '9',
            description: 'Here\'s a cocktail with a long history that inspired a slew of other drinks: the Gin Sour! It\'s the lesser known relative to sours like the Whiskey Sour and Amaretto Sour. But the Gin Sour is just as tasty as its cousins: it\'s smooth, tart, balanced, with floral notes from the gin. Top it with a classic egg white foam for a creamy body and frothy finish. It\'s a unique sour to remember! Here\'s how to make it.',
        },
        {
            name: 'Greyhound',
            id: '43',
            image: 'greyhound.jpg',
            ingredients:['gin', 'grapefruit juice', 'simple syrup', 'grapefruit wedge'],
            directions: 'Fill a glass with ice. Place the gin, grapefruit juice, and syrup in a cocktail shaker with 4 ice cubes and shake until cold. Strain it into the glass. Garnish with a grapefruit wedge and rosemary branch (if desired).',
            rating: '9',
            description: 'Here\'s a refreshingly tart drink: the Greyhound cocktail! It\'s citrusy and light, perfect as a brunch drink or for sipping at happy hour. It works in any season: it can be beachy for summer, or throw in a rosemary branch and use winter citrus! This dog-themed cocktail has just a few ingredients and is easy to mix up! Alex and I love making this classic gin cocktail for entertaining. Ready to taste?',
        },
        {
            name: '',
            id: '44',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '45',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: 'Aqua Velvet',
            id: '46',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '47',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '48',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '49',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '50',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '51',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '52',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '53',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '54',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '55',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: 'Aqua Velvet',
            id: '56',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '57',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '58',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '59',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '60',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '61',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '62',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '63',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '64',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '65',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: 'Aqua Velvet',
            id: '66',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '67',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '68',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '69',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
        {
            name: '',
            id: '70',
            image: '.jpg',
            ingredients:[''],
            directions: '',
            rating: '9',
            description: '',
        },
    ],
    ingredients: [
    {
        alcohol: [
            {
                wine: [
                    {
                        red: [
                            'cabernet sauvignon',
                            'pinot noir',
                            'red blends',
                            'malbec',
                            'merlot',
                        ],
                        white: [
                            'sauvignon Blanc',
                            'chardonnay',
                            'pinot grigio',
                            'moscato',
                            'riesling',
                        ],
                        sparkling: [
                            'champagne',
                            'prosecco',
                            'amercian sparkling',
                            'sparkling rose',
                        ],
                        pink_wine: [
                            'rose',
                            'white zinfadel',
                            'pink moscato',
                        ],
                        dessert_and_fortified: [
                            'port',
                            'dessert wine',
                            'vermouth',
                            'sherry',
                            'madeira',
                            'ice wine / eiswein',
                            'marsala',
                            'pedro zimenez',
                        ]
                    }
                ],
                spirits: [
                    {
                        whiskey: [
                            'bourbon',
                            'scotch whisky',
                            'irish whiskey',
                            'american whiskey',
                            'rye whiskey',
                            'japanese whisky',
                            'canadian whisky',
                            'flavored whiskey',
                        ]
                    },
                    {
                        tequila: [
                            'blanco',
                            'anejo',
                            'reposado tequila',
                            'gold',
                            'flavored',
                        ]
                    },
                    {
                        gin: [
                            'london dry',
                            'modern',
                            'genever / dutch',
                            'aged',
                            'old tom',
                            'navy strength',
                        ]
                    },
                    {
                        general_rum: [
                            'rum',
                            'aged rum',
                            'Flavored Rum',
                            'White Rum',
                            'Spiced Rum',
                            'Gold Rum',
                            'Dark Rum',
                        ]
                    },
                    {
                        brandy: [
                            'cognac',
                            'armagnac',
                            'fruit brandy',
                            'grappa',
                            'flavored brandy',
                            'eau de vie',
                            'calvados',
                            'pisco',
                        ]
                    },
                    {
                        liqueur: [
                            'fruit liqueur',
                            'cream liqueur',
                            'herbal liqueur',
                            'triple sec liqueur',
                            'amaretto liqueur',
                            'other liqueur',
                            'chocolate liqueur',
                            'coffee liqueur',
                            'anise liqueur',
                            'sloe gin',
                        ]
                    },
                    {
                        other: [
                            'vodka',
                            'mezcal',
                        ]
                    }
                ],
                beer: [
                    'IPA',
                    'hard seltzer',
                    'lager',
                    'light beer',
                    'ale',
                    'stout',
                    'sour beer',
                    'belgian',
                    'cider',
                    'hazy IPA',
                    'non-alcoholic',
                    'ginger beer',
                ]
            }
        ],
        mixers: [
            'lime juice',
            'orange juice',
            'lemon juice',
            'orange juice',
            'angostura',
            'pineapple juice',
            'apple juice',
            'simple syrup',
            'pomegranite juice',
            'egg white',
            'orange bitters',
            'cranberry juice',
            'club soda',
            'soda',
            'cream',
            'grapefruit juice',
            'milk',
        ],
        garnishes: [
            'olives',
            'maraschino cherries',
            'limes',
            'lemons',
            'rosemary',
            'salt',
            'cinnamon',
            'mint leaves',
            'celery',
            'cocktail onions',
            'cucumbers',
            'oranges',
            'whipped cream',
            'apples',
            'bananas',
            'candy',
            'chocolate',
            'pineapples',
            'strawberries',
        ]
    }
]
}

export default newData