const newData = {
    drinks: [
        {
            name: 'Dark & Stormy',
            id: '1',
            image: 'dark_and_stormy.jpg',
            ingredients: ['rum','ginger beer', 'lime juice'],
            directions: 'Fill a tall glass with ice cubes. Add rum, then pour in ginger beer and lime juice. Stir with a barspoon. Garnish with a lime wedge.',
            rating: '9',
            description: 'Sweet and sharp, the Dark and Stormy climbed out of the Bermuda Triangle to become one the most popular Caribbean rum cocktails you can make.',
        },
        {
            name: 'French 75',
            id: '2',
            image: 'french_75.jpg',
            ingredients: ['london dry gin','superfine sugar', 'lemon juice', 'brut champagne'],
            directions: 'Shake gin, sugar, and lemon juice well with cracked ice in a chilled cocktail shaker. Strain into a Collins glass half-full of cracked ice. Top off with champagne.',
            rating: '10',
            description: 'It looks like bubbly effervescence, but looks deceive. The French 75, with gin and champagne, packs a wallop, made all the more dangerous by how delightful it is to drink.',
        },
        {
            name: 'Boulevardier',
            id: '3',
            image: 'boulevardier.jpg',
            ingredients: ['bourbon','campari', 'sweet vermouth'],
            directions: 'Stir ingredients with ice in a mixing glass until chilled. Strain into a coupe glass. Garnish with an orange twist.',
            rating: '9',
            description: 'The Negroni\'s wintery counterpart is the Boulevardier, a whiskey cocktail invented for expat Americans bumming around Paris in the early 20th century.',
        },
        {
            name: 'Bloody Mary',
            id: '4',
            image: 'bloody_mary.jpg',
            ingredients: ['tomato juice','horseradish', 'worchestershire sauce', 'celery seeds', 'hot sauce', 'lemon juice', 'lime juice', 'salt', 'pepper', 'vodka'],
            directions: 'Blend tomato juice, horseradish, Worcestershire, and celery seeds until smooth. Add hot sauce, lemon juice, lime juice, salt, and pepper, then blend. Adjust the mix depending on how spicy, salty, or citrusy you like it. Add 1 tbsp. vodka to stabilize the mix and keep the juices fresh, then blend. Combine 6-8 oz. of the mix with 2 oz. of vodka into a glass with ice. Pour back and forth into another glass 3 or 4 times to mix, then garnish however you like.',
            rating: '8',
            description: 'Oh yeah, you can and should make your own Bloody Mary mix. It\'s labor intensive, sure, but it\'s highly customizable. You can decide just how you want the horseradish to play off the citrus that plays off the hot sauce heat.',
        },
        {
            name: 'Gimlet',
            id: '5',
            image: 'gimlet.jpg',
            ingredients: ['london dry gin','lime juice'],
            directions: 'Shake ingredients in a cocktail shaker with cracked ice. Strain into a chilled cocktail glass, and garnish with a lime.',
            rating: '9',
            description: 'Rose\'s lime cordial is perfectly balanced by herbaceous dry gin in this tart, impossible-to-screw-up British cocktail.',
        },
        {
            name: 'Moscow Mule',
            id: '6',
            image: 'moscow_mule.jpg',
            ingredients: ['vodka','ginger beer', 'lime juice'],
            directions: 'Squeeze lime juice into a Moscow Mule mug, then drop in spent shell. Add 2-3 ice cubes and vodka, then fill with ginger beer.',
            rating: '8',
            description: 'This cocktail is crisp and cooling, and good for any season. Plus it (usually) comes in a copper mug, which is neat.',
        },
        {
            name: 'Aperol Spritz',
            id: '7',
            image: 'aperol_spritz.jpg',
            ingredients: ['aperol','prosecco', 'club soda', 'orange slices'],
            directions: 'Build Aperol, prosecco, and club soda in a wine glass over ice. Garnish with fresh orange slices in the glass.',
            rating: '7',
            description: 'For daytime drinking, you really can\'t beat an Aperol Spritz. It\'s pretty basic, but then again, that\'s its charm. Just ask all the bar patrons crowding the patio around you, Spritzes in hand.',
        },
        {
            name: 'Mojito',
            id: '8',
            image: 'mojito.jpg',
            ingredients: ['white rum','lime juice', 'superfine sugar', 'mint leaves', ['club soda' || 'seltzer']],
            directions: 'In a smallish Collins glass, muddle lime juice with 1/2 to 1 tsp. superfine sugar. Add the mint leaves, mushing them against the side of the glass, then fill the glass 2/3 with cracked ice and pour in the rum. Pitch in the squeezed-out lime shell and top off with club soda or seltzer.',
            rating: '9',
            description: 'Really, it\'s difficult to imagine a combination more refreshing than rum, lime, mint, and bubbles. We have Cuba to thank, and thank heartily, for the Mojito.',
        },
        {
            name: 'Manhattan',
            id: '9',
            image: 'manhattan.jpg',
            ingredients: ['rye whiskey', 'italian vermouth', 'angostura bitters'],
            directions: 'Stir ingredients well with cracked ice, then strain into a chilled cocktail glass. Garnish with a twist or maraschino cherries.',
            rating: '9',
            description: 'A Manhattan is strong in all ways. The flavor is deep and unabashed, and the ABV is nothing to scoff at. It\'s a cocktail stalwart, and not for the weak of heart.',
        },
        {
            name: 'Margarita',
            id: '10',
            image: 'margarita.jpg',
            ingredients: ['silver tequila','cointreau', 'lime juice', 'salt'],
            directions: 'Rub the rim of a chilled cocktail glass with lime juice and dip in coarse salt. Shake tequila, Cointreau, lime juice, and ice in a mixing glass, then strain into the salted glass over ice.',
            rating: '9',
            description: 'The Margarita is the workhorse of summer. It\'s best made with Cointreau, and if you like it a little sweeter, agave syrup is a killer addition.',
        },
        {
            name: 'Whickey Sour',
            id: '11',
            image: 'whiskey_sour.jpg',
            ingredients: [['bourbon' || 'rye'],'lemon juice', 'superfine sugar', 'egg white'],
            directions: 'Shake ingredients well with cracked ice, strain into a chilled cocktail glass, and garnish with a lemon wedge and/or maraschino cherries.',
            rating: '9',
            description: 'For those nights when you want to cleanse your palate, opt for a puckery Whiskey Sour. Bourbon is traditional, but rye can lend it some punch.',
        },
        {
            name: 'Dry Martini',
            id: '12',
            image: 'dry_martini.jpg',
            ingredients: ['dry vermouth','gin', 'olives'],
            directions: 'Fill a metal shaker with cracked ice. Pour in the dry vermouth, stir briefly, and strain out (this may be discarded). Add gin, then stir briskly for about 10 seconds. Strain into a chilled cocktail glass, and garnish with olives or a lemon twist.',
            rating: '9',
            description: 'A classic martini technically should be made with gin and served bone-chillingly cold. Order it stirred, not shaken. Sorry, 007.',
        },
        {
            name: 'Daiquiri',
            id: '13',
            image: 'daiquiri.jpg',
            ingredients: ['white rum','lime juice', 'superfine sugar'],
            directions: 'Squeeze lime into a shaker, stir in sugar, then add rum. Shake well with cracked ice and strain into a chilled cocktail glass.',
            rating: '6',
            description: 'A citrusy marriage of rum and lime in the Caribbean gave us the simple but satisfying Daiquiri. Strain it and serve it sans ice.',
        },
        {
            name: 'Negroni',
            id: '14',
            image: 'negroni.jpg',
            ingredients: ['london dry gin','campari', 'vermouth'],
            directions: 'Add the ingredients together in a cocktail shaker. Stir well with cracked ice. Strain into a glass over cubed ice, then garnish with a twist of orange peel.',
            rating: '9',
            description: 'The Negroni is the epitome of refined summer drinking: sweet and bitter and invigorating.',
        },
        {
            name: 'Old Fashioned',
            id: '15',
            image: 'old_fashioned.jpg',
            ingredients: [['bourbon' || 'rye whiskey'],'angostura bitters', 'sugar cube', 'club soda'],
            directions: 'Place sugar in an Old Fashioned glass. Wet it down with Angostura bitters and a splash of club soda, then muddle. Add a large ice cube and whiskey. Stir, then garnish with an orange twist.',
            rating: '9',
            description: 'The Old Fashioned is as classic as they come—the original whiskey cocktail. Even in the two centuries since its inception, it\'s still the most respected cocktail in the world, and not the least bit musty for its age. Rye will make it spicier than bourbon.',
        },
        {
            name: 'Mimosa',
            id: '16',
            image: 'mimosa.jpg',
            ingredients:['champagne', 'orange juice'],
            directions: 'Pour Champagne in Champagne flute, Add orange juice, Garnish with orange slice',
            rating: '9',
            description: 'The mimosa is the 4th most popular cocktail in the U.S. It\'s, unsurprisingly, most popular during the morning and afternoon. It\'s said that a bartender at the Ritz in Paris invented the mimosa in 1925. It\'s also said that it was invented around the turn of the 20th century in the Mediterranean. Though, that\'s maybe doing some disservice to the Spaniards who have been drinking orange juice and sparkling wine for centuries. Who can really say where these things come from? It gets its name from the yellow-flowering mimosa plant. That we do know. If you have a brunch service, expect to go through many wine bottle sizes or cases of wine on this cocktail.',
        },
        {
            name: 'Cosmopolitan',
            id: '17',
            image: 'cosmopolitan.jpg',
            ingredients:['vodka', 'cranberry juice', 'cointreau', 'lime juice'],
            directions: '    Pour vodka, cranberry juice, Cointreau, and lime juice into a shaker with ice cubes, shake, Strain into cocktail glass, Garnish with lime or lemon wheel',
            rating: '9',
            description: 'The cosmopolitan is credited to Toby Cecchini of Manhattan\'s The Odeon restaurant in 1987. In the grand scheme of cocktails, the cosmo is young. There is a similar recipe from the 1930s that calls for gin, Cointreau, lemon juice, and raspberry syrup. Like most cocktails, there are multiple sources claiming multiple creation stories. What we do know is that it gained popularity like mad in the 1990s on the back of Carrie Bradshaw and now single-handedly represents a certain type of social sophistication.',
        },
        {
            name: 'White Russian',
            id: '18',
            image: 'white_russian.jpg',
            ingredients:['coffe liquor', 'vodka', 'cream'],
            directions: 'Add ice to rocks or old-fashioned glass, Add coffee liqueur and vodka, Top off with cream, Tell them "the dude" sent you',
            rating: '9',
            description: 'The White Russian is a Black Russian with cream added. They have nothing to do with Russia besides their use of vodka. And vodka was created in Poland. Just one of those things, I guess. A Belgian named Gustave Tops invented the cocktail in 1949 in honor of the U.S. ambassador to Luxembourg\'s visit to Brussels. We\'ve now mentioned five countries in the last few sentences. You can be forgiven if you think the origin story of the White Russian doesn\'t follow a logical narrative thread.',
        },
        {
            name: 'Gin Fizz',
            id: '19',
            image: 'gin_fizz.jpg',
            ingredients:['gin', 'lemon juice', 'simple syrup', 'club soda'],
            directions: 'Pour all ingredients in a shaker with ice cubes, shake, Strain into an 8 oz. glass with no ice in it, Top with club soda, Garnish with lemon wedge or twist',
            rating: '9',
            description: 'The defining feature of a fizz, which is a family of cocktails, is the combination of acidic juice and fizzy water. Created in New Orleans around the 1870s, the drink became popular in the U.S. in the first half of the 20th century. It got so popular, in fact, that bars needed to hire entire teams of bartenders to take shifts making the darn things. And then around 1950, the domestic U.S. popularity couldn\'t contain itself. The drink went international. The rest is history. Folks usually put gin, whiskey, and in fizzes, but gin is the most popular. It\'s certainly one of our favorite classic cocktails.',
        },
        {
            name: 'Aqua Velvet',
            id: '20',
            image: 'aqua_velvet.jpg',
            ingredients:['vodka', 'gin', 'blue curacao', 'simple syrup', 'lemon juice', 'lemon wedge'],
            directions: 'Pour all ingredients into a glass, adding the soda water last (or sparkling lemonade). Garnish and serve. Pitcher variation: Add 1 cup vodka, 1 cup gin, ¾ cup blue curacao to a pitcher. Top off with 4 cups sparkling lemonade (or 1 cup simple syrup, 1 cup fresh lemon juice and 2 cups soda water). Serve over ice.',
            rating: '9',
            description: 'A drink inspired by aftershave? Yes, that\'s this bubbly bright blue masterpiece: the Aqua Velva! A child of the 1980\'s, it\'s got a searing neon color that belies its birth. While some versions of this cocktail can be sickly sweet, make it with fresh lemon juice and soda water and it\'s a refreshingly complex. The botanical notes in the gin shine though, pairing perfectly with the citrus of the blue curacao. It even tastes a teeny bit like… deliciously drinkable aftershave.',
        },
        {
            name: 'Aviation',
            id: '21',
            image: 'aviation.jpg',
            ingredients:['gin', 'lemon juice', 'maraschino liqueur', 'creme de violette','cherries'],
            directions: 'Add the gin, lemon juice, maraschino liqueur, and creme de violette to a cocktail shaker. Fill it with ice and shake it until cold. Strain into a cocktail glass. Garnish with a Luxardo cherry, if desired.',
            rating: '9',
            description: 'Here\'s a classic cocktail that\'s come back en vogue: the Aviation! This purple cocktail tastes as great as it looks: it\'s sweet tart, with a hint of cherry and a floral nuance that come from maraschino liqueur and creme de violette! To be honest, Alex and I had avoided this drink for quite a while because of the unique specialty ingredients. But that first sip was so intriguing that we immediately agreed: they\'re worth the purchase. It\'s a great drink for the adventurous home mixologist who doesn\'t mind adding another liqueur or two to their collection. Here\'s how to make it!',
        },
        {
            name: 'Basil Collins',
            id: '22',
            image: 'basil_collins.jpg',
            ingredients:['basil', 'cucumber', 'gin', 'simple syrup', 'lemon juice', 'soda water'],
            directions: 'In a cocktail shaker, muddle the basil leaves. Add the cucumber slices and muddle again.Add the gin, simple syrup, and lemon juice and fill the shaker with ice. Shake for 15 seconds until cold. Strain the drink into an ice-filled highball glass. Top with soda water and garnish with additional cucumber slices and basil.',
            rating: '9',
            description: 'Here\'s a deliciously bubbly drink that\'s calling your name (and ours too): the Basil Collins! This basil cocktail is a summer spin on the Tom Collins, featuring cucumber and that peppery fresh herb you might be growing in a pot or your garden. It\'s got a tangy sweet flavor, a cucumber basil essence and a load of bubbles packed in that glass. Add some jingling ice cubes, and it\'s a drink fit for flip flops and summer evenings.',
        },
        {
            name: 'Bees Knees',
            id: '23',
            image: 'bees_knees.jpg',
            ingredients:['gin', 'honey', 'simple syrup', 'lemon juice'],
            directions: 'Add the gin, lemon juice, and mix honey and simple syrup to a cocktail shaker. Fill with a handful of ice and shake until very cold. Strain the drink into a cocktail glass. Garnish with a lemon twist.',
            rating: '9',
            description: 'Here\'s a classy classic cocktail that\'s refreshing and sweet tart: the Bees Knees! It\'s got a cute 1920\'s name and a smooth flavor to match. The unique element? Honey syrup. Making simple syrup with honey instead of refined sugar adds a rich depth to cocktails. Combine it with lemon and gin, and you\'ve got a refreshing cocktail that goes down easy. Naturally sweet and perfectly balanced, it\'s easy to make too! Here\'s what you need to know.',
        },
        {
            name: 'Bijou',
            id: '24',
            image: 'bijou.jpg',
            ingredients:['gin', 'sweet vermouth', 'chartreuse', 'orange bitters', 'lemon peel'],
            directions: 'Combine the gin,sweet vermouth, Chartreuse and bitters in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Strain the drink into a cocktail glass. Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'Looking for a unique classic cocktail to impress? Try the Bijou cocktail! This drink is named for the colors of glittering jewels of the three liquors that make it up. It\'s been around for over a century, with a spirit-forward flavor that\'s crisp and herbaceous. Take one sip and you\'ll be reminded of a Manhattan. But it\'s even more interesting, with an herbal undertone to the finish. This one is full of surprises: and all your guests will be impressed. Here\'s how to make the Bijou!',
        },
        {
            name: 'Blood Orange Gin & Tonic',
            id: '25',
            image: 'blood_orange_gin_and_tonic.jpg',
            ingredients:['gin', 'blood orange juice', 'tonic water', 'mint'],
            directions: 'Add gin, blood orange juice, and ice and stir. Pour the tonic water onto a bar spoon into the glass (to increase the bubbles). Stir once. Add the garnishes and serve.',
            rating: '9',
            description: 'Here\'s arguably the easiest blood orange cocktail out there: the Blood Orange Gin and Tonic! There\'s nothing better than a cocktail you can mix up right in the glass, right? Much as we love a good blood orange margarita or blood orange martini…this one\'s even easier to make. Here the botanicals from the gin mesh perfectly with the bright citrus of the blood orange. It makes for a sunny twist on your favorite G&T! Here\'s how to make it!',
        },
        {
            name: 'Bramble',
            id: '26',
            image: 'bramble.jpg',
            ingredients:['gin', 'lemon juice', 'simple syrup','creme de mure', 'lemon slice', 'blackberry'],
            directions: 'Add crushed ice to a lowball glass. Add the gin, lemon juice and simple syrup to a cocktail shaker. Fill it with ice and shake until cold. Strain the drink into the glass with crushed ice. Drizzle the creme de mure over crushed ice. Garnish with a lemon slice and afresh blackberry.',
            rating: '9',
            description: 'Here\'s a special cocktail that solidified itself as a new favorite at first sip: the Bramble cocktail! This drink has the sweetest name and it\'s full of tangy, fruity and sophisticated flavors. This refreshing drink uses a special blackberry liqueur called crème de mûre. It might not be on hand in your liquor cabinet, but it should be: one swig is like a bite of fruity blackberry candy! This drink is one of the great modern classic gin cocktails…and to us, it\'s near perfection in a glass.',
        },
        {
            name: 'Clover Club',
            id: '27',
            image: 'clover_club.jpg',
            ingredients:['gin', 'grenadine', 'lemon juice', 'egg white', 'raspberry', 'lemon twist'],
            directions: 'Add the gin, raspberry syrup or grenadine, lemon juice, and egg white to a cocktail shaker without ice. Shake for 15 seconds. Add the ice to the cocktail shaker. Shake again for 30 seconds. Strain the drink into a cocktail glass; the foam will collect at the top. Garnish with a lemon twist or fresh raspberries.',
            rating: '9',
            description: 'Here\'s a sophisticated classic cocktail that steals the show: the Clover Club! This bright pink drink stems back before Prohibition, but it\'s just as en vogue today. Sweet raspberry or grenadine syrup combine with zingy lemon and gin to make a perfectly balanced sweet tart drink. The best part: a classic egg white foam gives a creamy body and frothy texture to each sip! This one\'s a unique gin cocktail that\'s just plain fun. We often make gin cocktails like the Gin Fizz: the one\'s a colorful variation on the theme.',
        },
        {
            name: 'Corpse Reviver No. 2',
            id: '28',
            image: 'corpse_reviver_no_2.jpg',
            ingredients:['gin', 'lemon juice', 'cointreau', 'dry vermouth', 'absinthe', 'orange peel'],
            directions: 'Add the gin, lemon juice, Cointreau, dry vermouth, and absinthe to a cocktail shaker. Fill it with ice and shake it until cold. Strain into a cocktail glass. If desired, garnish with an orange peel or orange wedge. ',
            rating: '9',
            description: 'Here\'s a classic cocktail that\'s as unique as its name…the Corpse Reviver No 2! To be honest, we were a little wary of this cocktail at first because of its moniker. But it turns out that the Corpse Reviver has nothing scary or ghoulish about it. In fact, it\'s damn good. It\'s a classic gin sour cocktail that\'s tart and zingy from lemon juice and orange liqueur, with a hint of licorice on the finish. It\'s truly a stunner…and the name will impress all your friends. Let\'s get mixing!',
        },
        {
            name: 'Cynar Negroni',
            id: '29',
            image: 'cynar_negroni.jpg',
            ingredients:['gin', 'vermouth', 'cynar', 'lemon peel'],
            directions: 'Combine the gin, sweet vermouth, and Cynar in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Add ice to a lowball glass, and strain the drink into the glass. Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'When it comes to Negroni variations, we tend to like them even better than the original. Such is the case with the Cynar Negroni! This intriguing spin features Cynar, an Italian amaro with hints of caramel, toffee and an herbal bitter finish. It makes a bitter, mellow Negroni that\'s more interesting to drink, in our opinion! Here\'s how to make it, and a few notes about this unique liqueur.',
        },
        {
            name: 'Dirty Martini',
            id: '30',
            image: 'dirty_martini.jpg',
            ingredients:['gin', 'dry vermouth', 'olive juice', 'olives'],
            directions: 'Combine the gin, vermouth, and olive juice in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds until very cold. Strain the drink into a cocktail or martini glass (purists chill the glass first). Garnish with an olive.',
            rating: '9',
            description: 'The martini is one of the most iconic cocktails of all time. The classic martini is just two ingredients: crisp, cool, and spirit-forward. But how to make it even more perfect? The Dirty Martini! Add a splash of olive juice to your martini, and the way it rounds out the flavor is true perfection. It\'s tangy, salty, briny and complex. The martini is seeped in tradition, and as you might expect: we have our own opinion on how to make it perfectly. Here\'s how to make a classic Dirty Martini…the best way.',
        },
        {
            name: 'Gibson',
            id: '31',
            image: 'gibson.jpg',
            ingredients:['gin', 'dry vermouth', 'cocktail onions'],
            directions: 'Combine the gin and vermouth in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds until very cold. Strain the drink into a cocktail or martini glass (purists chill the glass first). Garnish with cocktail onions.',
            rating: '9',
            description: 'Calling all martini lovers! Have you met the Gibson cocktail? This classic gin drink is essentially a martini with an onion garnish. This switch up on the classic “lemon or olive” garnish brings a savory element that makes it an altogether new drink. The Gibson is crisp, cool, searing, and spirit-forward, punctuated by the pungent onion garnish. Move over, Classic Martini: there\'s a new drink in town.',
        },
        {
            name: 'Gin & Coke',
            id: '32',
            image: 'gin_and_coke.jpg',
            ingredients:['gin', 'cola','lime juice', 'angostura bitters'],
            directions: 'Add the gin and ice to a glass and stir to combine. Top with the cola. Squeeze in the juice from the lime wedge (or ½ ounce lime juice) and serve. Garnish with additional lime wedges or wheels. ',
            rating: '9',
            description: 'Looking for an easy gin cocktail that tastes better than the sum of its parts? Try the Gin and Coke! Sure, the Gin and Tonic is probably the first easy gin drink that jumps to mind. But mixing this botanical liquor with cola is a very good idea. Use the right ratio and the delicate flavor of gin shines through without getting overpowered by the sweet cola. Add a zing of lime and it tastes totally novel. Move over, rum and coke. Gin\'s got the spotlight!',
        },
        {
            name: 'Gin & Lemonade',
            id: '33',
            image: 'gin_and_lemonade.jpg',
            ingredients:['gin', 'lemonade', 'mint', 'lemon slice'],
            directions: 'In a glass, pour in the lemonade and gin. Add ice and garnish with fresh mint and lemon slices.',
            rating: '9',
            description: 'Need an easy 2 ingredient cocktail idea with gin? Try this Gin and Lemonade! It might sound overly simple, but gin and lemon are a natural cocktail pairing featured in many classic drinks. What do the Tom Collins, Gin Fizz, and French 75 have in common? They all pair gin and lemon! If you\'re in the mood for a laid back version of these drinks, simply stir together gin and lemonade.',
        },
        {
            name: 'Gin & Soda',
            id: '34',
            image: 'gin_and_soda.jpg',
            ingredients:['gin', 'soda water', 'lime wedge'],
            directions: 'Add the gin, and ice to the glass and stir gently. Top with the soda water and a squeeze of lime juice. Serve immediately.',
            rating: '9',
            description: 'Looking for a fast and easy gin cocktail? Try Gin and Soda! Adding club soda to gin lets you enjoy the botanical intrigue of the flavor: and it takes no time at all to mix up. This cocktail is no new idea: it\'s very similar to the Gin Rickey, a classic drink from the 1880\'s. It\'s a refreshing drink that just so happens to be low calorie, too.',
        },
        {
            name: 'Gin & Tonic',
            id: '35',
            image: 'gin_and_tonic.jpg',
            ingredients:['gin', 'tonic water'],
            directions: 'Add lots of ice to a large cocktail or wine glass and stir to chill the glass. Drain any melted water.Pour in the gin. Add the garnishes. Pour the tonic water onto a bar spoon into the glass (to increase the bubbles). Stir once and serve.',
            rating: '9',
            description: 'What\'s more refreshing than a gin and tonic? Its crisp, botanical flavor is straightforward but at the same time intriguing: a feat using only 2 ingredients! It\'s no wonder that this is one of the world\'s popular cocktails. We\'ve researched to gather a few tips about making the perfect gin and tonic. Keep reading for our secrets.',
        },
        {
            name: 'Gin Fizz',
            id: '36',
            image: 'gin-fizz.jpg',
            ingredients:['gin', 'lemon syrup', 'simple syrup', 'egg white', 'lemon twist'],
            directions: 'Place the gin, lemon juice, syrup and egg white in a cocktail shaker. Shake vigorously for 15 seconds. Fill the shaker with ice and shake for 30 seconds until cold. Strain the drink into a glass and top with the soda water; the egg white foam forms on top. If desired, garnish with a lemon twist. Serve immediately.',
            rating: '9',
            description: 'Ever had a Gin Fizz? It\'s one of the best uses of a bottle of gin around (really). This classic cocktail from the 1870\'s is perfectly balanced, both sweet and tart with a pop of lemon and a botanical finish. Add to that a frothy egg white foam topping, which adds the best creamy texture to each sip. Oh and it takes only 5 minutes to make! Ready to experience this iconic gin cocktail?',
        },
        {
            name: 'Gin Gimlet',
            id: '37',
            image: 'gin_gimlet.jpg',
            ingredients:['gin', 'lime juice', 'simple syrup', 'soda water'],
            directions: 'Add gin, lime juice, and syrup to a cocktail shaker. Fill with ice and shake until cold. Strain into glass and top with a splash of soda water, if desired. Garnish with a lime wheel and serve.',
            rating: '9',
            description: 'Here\'s a classic cocktail that is super refreshing and takes only 5 minutes to whip up: the gimlet! Not only is the gimlet simple to make, it\'s the perfect balance of sweet and tart with the botanical flavor of gin. Alex and I got our hands on a bottle of local gin and have been mixing up all sorts of gin cocktails: a classic Gin and Tonic, Watermelon Gin Cocktails, a Hanky Panky, and the Gin Fizz. For our latest gin drink we decided to go retro and go with a gin gimlet cocktail: and it was even better than expected.',
        },
        {
            name: 'Gin & Basil',
            id: '38',
            image: 'gin_and_basil.jpg',
            ingredients:['basil leaf', 'gin', 'lime juice', 'lemon juice', 'simple syrup'],
            directions: 'Add the basil leaves to a cocktail shaker and gently muddle 4 to 5 times until the oil is released, but the basil is not broken. Add the remaining ingredients to the cocktail shaker. Fill it with ice and shake until cold. Strain the drink into a glass. Garnish with a fresh basil leaf.',
            rating: '9',
            description: 'Love fresh basil? Us too. Here\'s our new favorite way to use it: this Basil Cocktail! The peppery green herb adds a beautifully fresh flavor to this drink. It\'s a lemon lime gin drink: crisp and cool, with a sweet tart flavor. When Alex handed it to me and I took the first sip, I was sold. There\'s nothing better than basil in the summer, and we think this is just the way to use it. (Or a Basil Gimlet.) Here\'s how to use basil in cocktails, and the recipe for this lovely green drink.',
        },
        {
            name: 'Gin Basil Smash',
            id: '39',
            image: 'gin_basil_smash.jpg',
            ingredients:['basi leaf', 'gin', 'lemon juice0', 'simple syrup'],
            directions: 'Place the basil leaves in a cocktail shaker and muddle them (gently mash). Add the gin, lemon juice and simple syrup to the cocktail shaker. Add 2 handfuls ice and shake until cold. Strain the drink into an ice-filled lowball glass. If desired, top with splash of soda water. Garnish with additional basil leaves.',
            rating: '9',
            description: 'Got basil? Love gin? Here\'s the ideal drink for you: the Gin Basil Smash! This modern spin on the Whiskey Smash is light and herbaceous, pairing peppery basil with botanical gin. If there\'s summer in a cocktail glass, this is it! We love drinking our herbs all season long, and this new addition to our summer cocktails perfectly captures that feeling of fresh cut grass between your toes and sticky melted popsicle fingers. (At least, we think so!)',
        },
        {
            name: 'Gin Gin Mule',
            id: '40',
            image: 'gin_gin_mule.jpg',
            ingredients:['mint', 'lime juice', 'gin', 'ginger beer', 'lime wedge'],
            directions: 'Gently muddle (mash) the mint sprigs in the bottom of the mug using a cocktail muddler or wooden spoon. Add the lime juice, simple syrup and gin. Stir to combine. Add ice and the ginger beer and stir gently. Garnish with lime and mint',
            rating: '9',
            description: 'It\'s minty, it\'s bubbly, it\'s refreshing: meet the Gin Gin Mule! You might think it\'s a just liquor swap in a mule, but this cocktail is more than meets the eye! Considered a modern classic cocktail, it\'s a mashup of the Moscow mule and minty Mojito. You\'ve got the bubbly ginger beer and lime of a mule, balanced by the muddled mint and sweetness of a mojito. The Gin Gin Mule results in a much more balanced drink than it\'s classic counterpart. It\'s become a big favorite around here! Here we\'ll show you how to make this signature drink and a Moscow mule with gin.',
        },
        {
            name: 'Gin Rickey',
            id: '41',
            image: 'gin_rickey.jpg',
            ingredients:['gin', 'lime juice', 'soda water', 'lime wedge'],
            directions: 'Add the gin and lime juice to highball glass and stir. Fill with ice and top with sparkling water. Garnish with a lime wedge.',
            rating: '9',
            description: 'It\'s tall, it\'s bubbly, and it\'s one of the easiest to make cocktails out there. Try the Gin Rickey! This classic cocktail was born in the 1880s and has been popular ever since. And for good reason: it\'s tangy, bubbly, and irresistibly delicious. If you love a Vodka Soda or a Gin and Tonic: this is the drink for you! There\'s no frills: just a classy classic highball. Alex and I love sipping on these afternoons on the patio — along with the rickey\'s many variations. Here\'s how to make it!',
        },
        {
            name: 'Gin Sour',
            id: '42',
            image: 'gin_sour.jpg',
            ingredients:['gin', 'lemon juice', 'egg white', 'simople syrup', 'angostura bitters'],
            directions: 'Add the gin, lemon juice, syrup, and egg white to a cocktail shaker without ice. Shake for 15 seconds. Add the ice to the cocktail shaker. Shake again for 30 seconds. Strain the drink into a glass; the foam will collect at the top. Serve with or without ice. Garnish with bitters swirled into foam and lemon twist.',
            rating: '9',
            description: 'Here\'s a cocktail with a long history that inspired a slew of other drinks: the Gin Sour! It\'s the lesser known relative to sours like the Whiskey Sour and Amaretto Sour. But the Gin Sour is just as tasty as its cousins: it\'s smooth, tart, balanced, with floral notes from the gin. Top it with a classic egg white foam for a creamy body and frothy finish. It\'s a unique sour to remember! Here\'s how to make it.',
        },
        {
            name: 'Greyhound',
            id: '43',
            image: 'greyhound.jpg',
            ingredients:['gin', 'grapefruit juice', 'simple syrup', 'grapefruit wedge'],
            directions: 'Fill a glass with ice. Place the gin, grapefruit juice, and syrup in a cocktail shaker with 4 ice cubes and shake until cold. Strain it into the glass. Garnish with a grapefruit wedge and rosemary branch (if desired).',
            rating: '9',
            description: 'Here\'s a refreshingly tart drink: the Greyhound cocktail! It\'s citrusy and light, perfect as a brunch drink or for sipping at happy hour. It works in any season: it can be beachy for summer, or throw in a rosemary branch and use winter citrus! This dog-themed cocktail has just a few ingredients and is easy to mix up! Alex and I love making this classic gin cocktail for entertaining. Ready to taste?',
        },
        {
            name: 'Finnish Long Drink',
            id: '44',
            image: 'finnish_long_drink.jpg',
            ingredients:['gin', 'lemon juice','cranberry juice', 'grapefruit soda', 'grapefruit wedge'],
            directions: 'In an ice-filled highball glass, stir together the gin, lemon juice, and cranberry juice. Top with the grapefruit soda. Garnish with a grapefruit wedge, if desired. ',
            rating: '9',
            description: 'Heres a unique highball cocktail that we highly recommend giving a try: the Finnish Long Drink! This concoction of gin and usually grapefruit soda was invented in Finland in the 1950s, and you can find it everywhere in country. Its now becoming available canned in the US: but why not make it homemade? This spin is easy to make and so fizzy, sweet tart and refreshing, we couldnt help but take another sip.',
        },
        {
            name: 'French 77',
            id: '45',
            image: 'french_77.jpg',
            ingredients:['elderflower liqueur', 'lemon juice', 'champagne', 'lemon twist'],
            directions: 'Pour the St Germain and lemon juice into a champagne glass. Fill it with sparkling wine. Garnish with a lemon twist.',
            rating: '9',
            description: 'Looking for a festive drink? Try the French 77! This champagne cocktail is a spin on the classic French 75 that adds St Germain elderflower liqueur. And dare we say it: it makes this classic cocktail even better. Its bubbly and effervescent, with the floral undertones and the zing of fresh lemon juice. If you need a signature cocktail to impress your friends, this is the one.',
        },
        {
            name: 'French Gimlet',
            id: '46',
            image: 'french_gimlet.jpg',
            ingredients:['gin', 'st germain', 'lime juice', 'lime wedge'],
            directions: 'Add gin, lime juice, and St Germain to a cocktail shaker. Fill with a handful of ice and shake until cold. Strain into glass. Garnish with a lime wedge and serve.',
            rating: '9',
            description: 'Heres a sophisticated cocktail thats refreshing and perfectly tart: the French gimlet! Just three ingredients go into this chic drink, and its a fun way to mix up cocktail night. This has become my favorite gimlet (we have 3!) because of warm floral flavor of the elderflower liqueur. If youre never had St Germain, this is a great drink to start with. Heres how to make it!',
        },
        {
            name: 'Floradora',
            id: '47',
            image: 'floradora.jpg',
            ingredients:['gin', 'raspberry syrup', 'lime juice', 'ginger beer', 'lime wedge', ],
            directions: 'In a highball glass or stemmed glass, add the gin, raspberry syrup or Chambord, and lime juice. Fill with ice and top with ginger beer. Garnish with a lime wedge and raspberry, if desired.',
            rating: '9',
            description: 'Heres a light, bubbly classic cocktail thats flown under the radar for too long: the Floradora! This beautifully pink drink was inspired by a Broadway show by the same name and dates back to the early 1900s. Its a total gem of a drink: raspberry syrup pairs beautifully with lime, gin, and the spicy kick of ginger beer! Its a classic highball cocktail, though its relatively undiscovered. With its sweet name and delicious sweet tart flavor, we think its time for another spot in the limelight!',
        },
        {
            name: 'Hanky Panky',
            id: '48',
            image: 'hanky_panky.jpg',
            ingredients:['gin', 'sweet vermouth', 'fernet-branca', 'orange twist'],
            directions: 'Combine the gin, sweet vermouth, and Fernet-Branca in cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Strain into a glass. Garnish with an orange twist and serve.',
            rating: '9',
            description: 'Heres a sophisticated cocktail that will have all your friends talking about it: the Hanky Panky cocktail! Its complex and nuanced, with a smooth flavor perfect for sipping. The star here is Fernet-Branca, an Italian bitter that adds an herbal punch. The cocktail is perfectly balanced: a little sweet and a little bitter, which makes it irresistible. Heres how to make it, and a little more about the origin of the name. Because, whats more fun than ordering a “Hanky Panky”?',
        },
        {
            name: 'Last Word',
            id: '49',
            image: 'last_word.jpg',
            ingredients:['gin', 'green chartreuse liqueur', 'maraschino liqueur', 'lime juice', 'cherries'],
            directions: 'Add the gin, Chartreuse, maraschino liqueur, and lime juice to a cocktail shaker. Fill it with ice and shake it until cold. Strain into a cocktail glass. Garnish with a Luxardo cherry or cocktail cherry.',
            rating: '9',
            description: 'Heres a drink for the adventurous home bartender: the Last Word cocktail! This pale green gin sour is a classic cocktail that was all but lost to history. But with the revival of cocktail culture, this ones come back strong! Its equal parts sharp, sweet, and sour: full of intrigue and nuance from a few special ingredients. Because Im partial to green drinks and sour cocktails, this one hit it home for me! Heres all about this forgotten classic.',
        },
        {
            name: 'Lavender Gin',
            id: '50',
            image: 'lavender_gin.jpg',
            ingredients:['gin', 'lavender simple syrup', 'lemon juice', 'soda water', 'lemon slice'],
            directions: 'Add the gin, syrup and lemon juice to a cocktail shaker with 4 ice cubes. Shake well until chilled. Strain the liquid into an ice filled glass, and top off the glass with soda water. Garnish with a lemon wheel and cocktail cherry.',
            rating: '9',
            description: 'Heres an herbal, sweet tart cocktail thats a new favorite around here: this Lavender Collins Cocktail! Its a spin on the classic Tom Collins starring this fresh herb. And wow, is it full of flavor! Its sweet tart, zing and bubbly, with a subtle floral finish to each sip. Its got just the right essence of lavender that leaves you wanting more. Alex and I have been making a string of lavender drinks, and this one is at the top of the list. Heres what to know about making a lavender cocktail.',
        },
        {
            name: 'Lillet Cocktail',
            id: '51',
            image: 'lillet_cocktail.jpg',
            ingredients:['gin', 'lillet blanc', 'tonic water', 'mint'],
            directions: 'Add lots of ice to a large cocktail or wine glass and stir to chill the glass. Drain any melted water. Pour in the gin and Lillet Blanc. Add the garnishes. Pour the tonic water onto a bar spoon into the glass (to increase the bubbles). Stir once and serve.',
            rating: '9',
            description: 'Heres a memorable cocktail thats botanical and bubbly: the Lillet G&T! This Lillet cocktail features the popular fortified wine dressed up as a Gin and Tonic. And man, does it deliver! The flavor is perfectly crisp, with floral and herbal notes from Lillet Blanc and the gin. Top that off with lots of bubbles, and youve got a refreshing cocktail that works not only for summer afternoons but evening happy hour in any season. Heres how to make it!',
        },
        {
            name: 'Lime Rickey',
            id: '52',
            image: 'lime_rickey.jpg',
            ingredients:['lime juice', 'gin', 'sodaw water', 'lime wedge'],
            directions: 'Add the lime juice and alcoholic or non-alcoholic mixer (whiskey, gin, caper juice or simple syrup) to highball glass and stir. Fill with ice and top with sparkling water. Garnish with lime wedges.',
            rating: '9',
            description: 'Heres a bubbly drink thats equally as refreshing as a cocktail or mocktail: the Lime Rickey! This refreshing drink is a cousin of the classic Gin Rickey, though some people consider it the same drink. Others say the lime version is a virgin drink. Whatever your definition: weve got a recipe! Make it with gin or whiskey, or use our mocktail substitutes. Take one sip and its fizzy, bubbly, and ultra tangy: with effect of jumping into a cold pool on a hot summer day. Heres how to make it: whatever way you choose!',
        },
        {
            name: 'Long Island Iced Tea',
            id: '53',
            image: 'long_island_ice_tea.jpg',
            ingredients:['vodka', 'tequila', 'white rum', 'gin', 'cointreau', 'lemon juice','cola','lemon wedge'],
            directions: 'Combine all ingredients in highball glass. Fill it with ice and stir. Garnish and serve. ',
            rating: '9',
            description: 'Some cocktails have a strong image, and the Long Island Iced Tea is one of them, right? Its boozy, low-brow, and sickly sweet, with strong chain restaurant vibes. But have you tried a classic Long Island Iced Tea? Mixed up as intended, this drink will blow you away. Ditch the sour mix and Triple Sec in favor of fresh citrus and top shelf liquor. One sip and its zingy, sweet tart, nuanced and sophisticated. This is one classy Long Island Iced Tea: and well show you exactly how to make it!',
        },
        {
            name: 'Martinez',
            id: '54',
            image: 'martinez.jpg',
            ingredients:['gin', 'sweet vermouth', 'marashino liqueur', 'angostura bitters', 'orange peel'],
            directions: 'Combine the gin, sweet vermouth, and Maraschino liqueur in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Strain the drink into a cocktail glass. Use a knife to remove a strip of the orange peel. Squeeze the orange peel into the drink to release the oils. Gently run the peel around the edge of the glass. If desired, twist it, then place it in the glass and serve.',
            rating: '9',
            description: 'Heres a drink thats classy and complex: the Martinez! This classic cocktail is in the spirit-forward cocktail family, a cousin of the Martini and the Manhattan. To us, its an improvement on both! Theres so much going on flavor-wise. Its balanced and just sweet enough, with notes of cherry and cinnamon, and a little spice at the finish. This cocktail hasnt caught on in the same way as its cousins: but it absolutely deserves a place at the table.',
        },
        {
            name: 'Ramos Gin Fizz',
            id: '55',
            image: 'ramos_gin_fizz.jpg',
            ingredients:['gin', 'lemon juice', 'lime', 'simple syrup', 'heavy cream', 'orange flower water', 'egg white', 'soda water', 'lemon wedge'],
            directions: 'Add the gin, lemon juice, lime juice, simple syrup, heavy cream, orange flower water, and egg white to cocktail shaker without ice. Shake for 15 seconds (called a “dry shake). Add ice to the cocktail shaker. Shake again for 30 to 45 seconds. Strain the drink into an ice filled Collins glass or highball glass. Add a splash of soda water into the glass and allow to sit for 1 minute until foam separates. ',
            rating: '9',
            description: 'Heres an over-the-top impressive classic cocktail: the Ramos Gin Fizz! The impossibly tall frothy topping and tangy burst of lime, lemon and orange blossom water makes it taste just like a lemon meringue pie. Is the Ramos Gin Fizz better than the classic Gin Fizz? Absolutely. In all honesty, we didnt think anything could beat the classic. But one sip of this one, and youll realize just how special this drink is.',
        },
        {
            name: 'Red Snapper',
            id: '56',
            image: 'red_snapper.jpg',
            ingredients:['tomato juice', 'lemon juice', 'worcestershire sauce', 'horeradish', 'tobasco', 'celery salt', 'gin', 'black pepper', 'old bay seasoning', 'celery', 'lemon wedge', 'olives', 'cocktail onions'],
            directions: 'If time allows, chill the tomato juice and gin. Shake the tomato juice before pouring. In a large cocktail shaker, combine the tomato juice, lemon juice, Worcestershire sauce, horseradish, Tabasco, celery salt and black pepper. Shake well to combine (without ice). Strain into a quart mason jar or small pitcher. Optional: If time, chill at least 1 hour or overnight for the best flavor. (Or, make ahead and store up to 1 week.) But you also can serve right away! To serve, on a plate place a mixture of roughly half kosher salt and half Old Bay seasoning (or celery salt). Cut a notch in a lemon wedge, then run it around the rim of a glass. Dip the edge of the rim into a plate of salt. To each glass, add 2 ounces (¼ cup) gin and ½ cup of Red Snapper mix and stir gently to combine. Fill the glass with ice and add the garnishes.',
            rating: '9',
            description: 'Heres a tasty spin on a classic: the Red Snapper cocktail! The name doesnt betray this drink: though its both red and snappy. But its holding a secret: its essentially a classic Bloody Mary with gin. Switching out the vodka leads to a whole new drink: savory, spicy, tangy, spicy, with a hint of botanical on the finish from the gin. Its a fun variation on the standard: and even more so to surprise your guests with this unique spin.',
        },
        {
            name: 'Pegu Club',
            id: '57',
            image: 'pegu_club.jpg',
            ingredients:['gin', 'orange liqueur', 'lime juice', 'angostura bitters', 'orange bitters', 'lime wedge'],
            directions: 'Place the gin, orange liqueur, lime juice, and bitters in a cocktail shaker. Add 2 handfuls of ice and shake until cold. Strain the drink into a cocktail glass. Garnish with a lime wedge if desired.',
            rating: '9',
            description: 'After trying 300+ homemade cocktails, its not often to find one that surprises us. But this one was not what we expected. Meet the Pegu Club cocktail! Its a classic 1920s drink invented at, as the name suggests, the Pegu Club. This boozy drink is sophisticated and refreshing, with a citrus and herbal finish. Its surprisingly balanced but not sweet at all (though it might look like a sour cocktail). Heres how to make this intriguing classic…that we think deserves a revival.',
        },
        {
            name: 'Pomegranite Gin Fizz',
            id: '58',
            image: 'pomegranite_gin_fizz.jpg',
            ingredients:['gin', 'pomegranite juice', 'lemon juice', 'simple syrup', 'egg white', 'soda water', 'rosemary sprig'],
            directions: 'Place the gin, POM juice, lemon juice, simple syrup and egg white in a cocktail shaker. Shake vigorously for 15 seconds. Fill the shaker with ice and shake for 30 seconds until cold. Strain the drink into a glass and top with the soda water; the egg white foam forms on top. If desired, garnish with a rosemary sprig. Serve immediately.',
            rating: '9',
            description: 'Heres an impressive cocktail thats pretty darn perfect, in our opinion: this Pomegranate Gin Fizz! The Gin Fizz is one of our favorite classic cocktails: sweet tart and refreshing, with a festive egg white foam. Take it over the top with this pomegranate spin: it elevates the sweet tart flavor and gives the drink a brilliant jewel-toned color! Here we used POM Wonderful 100% Pomegranate Juice to make this deliciously festive cocktail. It will impress absolutely everyone (we promise!): for the holidays or in any season.',
        },
        {
            name: 'Salty Dog',
            id: '59',
            image: 'salty_dog.jpg',
            ingredients:['sea salt', 'gin', 'grapefruit juice', 'simple syrup', 'lime wedge', 'grapefruit wedge'],
            directions: 'Cut a notch in the lime wedge, then run the lime around the rim of a glass. Dip the edge of the rim into a plate of flaky sea salt. Place the gin, grapefruit juice and syrup in a cocktail shaker with 4 ice cubes and shake until cold. Strain the drink into the glass with the salted rim. Fill the glass with ice and top with a squeeze of lime. Garnish with a grapefruit wedge.',
            rating: '9',
            description: 'Want a citrus cocktail with a salted rim thats not a margarita? Enter, the Salty Dog! This cocktails got a unique name and a beautiful pale pink color. Its really not anything like a margarita, aside from that salt rim! Its tangy and refreshing, perfect as a brunch drink or for happy hour. Its got a light summery vibe, but it works in winter when citrus abounds. Really, it works anytime! (Plus, how fun it is to say “Lets make Salty Dogs!”?)',
        },
        {
            name: 'Singapore Sling',
            id: '60',
            image: 'singapore_sling.jpg',
            ingredients:['gin', 'cherry liqueur', 'cointreau', 'lime juice', 'benedictine', 'grenadine', 'pineapple juice', 'angosturra bitters', 'soda water', 'cocktail cherry'],
            directions: 'Add all ingredients to a cocktail shaker. Fill it with ice and shake it until cold. Strain the drink into a hurricane or highball glass thats filled with ice. Top with splash of soda water (about 1 ounce or so). Garnish with a cocktail cherry and orange wedge.',
            rating: '9',
            description: 'Want an impressive cocktail thats fruity and refreshing? Try the Singapore Sling! This ones for the adventurous drinker because it calls for a whopping 8 ingredients! Its the longest ingredient list of any of our cocktail recipes and has a few specialty ingredients. But if you want to experience a classic cocktail and dont mind the challenge: its a must try! The combination of fruity, sweet tart and bubbly is intriguingly complex and just plain fun.',
        },
        {
            name: 'Southside',
            id: '61',
            image: 'southside.jpg',
            ingredients:['mint', 'gin', 'lime juice', 'lemon juice', 'simple syrup', 'lemon twist', 'mint leaves'],
            directions: 'Add the mint leaves to a cocktail shaker and muddle them. Add the gin, lemon juice, lime juice and syrup to cocktail shaker. Fill it with ice and shake until cold. Strain the drink into chilled cocktail glass. Garnish with an additional mint leaf (smack it between your hands to release the oils) and a lemon twist.',
            rating: '9',
            description: 'Every time we make another cocktail, I say its our new favorite. But this one really is our new favorite! Meet the Southside cocktail. Its minty, fresh, and botanical, made with lemon, lime, and gin. Its sweetened just enough: crisp, cool and refreshing. Its perfect for sipping on a cocktail night with friends, or an afternoon cocktail on the patio. Alex and I recently made them for cocktail night with some dear friends, and they got a chorus of “Wows!” (thanks, Lauren!). Really: theres no better time to make yourself a Southside than now! Ready to get started?',
        },
        {
            name: 'Southside Fizz',
            id: '62',
            image: 'southside_fizz.jpg',
            ingredients:['mint leaves', 'gin', 'lemon juice', 'lime juice', 'simple syrup', 'soda water', 'lemon peel'],
            directions: 'Add the mint leaves to a cocktail shaker and muddle them (see How to Muddle Mint). Add the gin, lemon juice, lime juice and syrup to cocktail shaker. Fill with ice and shake until cold. Strain into chilled highball glass. Top with soda water and garnish with an additional mint leaf (smack it between your hands to release the oils) and lemon peel.',
            rating: '9',
            description: 'Heres one of the most refreshing cocktails out there: a Southside Fizz! A cousin of the Southside Cocktail, this gin cocktail features bright citrus, herbaceous mint, and fizzy soda water. Its tart and fizzy, perfect for drinks on the patio, a daytime brunch drink, or a wintertime cocktail when youre dreaming of summer. Alex and I are big fans of citrus cocktails (the Margarita, Paloma, and Lime Daiquiri are all at the top of our list). So this Southside Fizz is right up our alley. Heres how to make it!',
        },
        {
            name: 'Tom Collins',
            id: '63',
            image: 'tom_collins.jpg',
            ingredients:['gin', 'simple syrup', 'lemon juice', 'soda water', 'maraschino cherries', 'lemon wedge'],
            directions: 'Add the gin, syrup and lemon juice to a cocktail shaker with 4 ice cubes. Shake well until chilled. Strain the liquid into an ice filled glass, and top off the glass with soda water. Garnish with a lemon wheel and cocktail cherry.',
            rating: '9',
            description: 'Ahh, the Tom Collins: this nostalgic cocktail is about as classic as it gets! This tall highball drink is a essentially gin sour, a sweet and sour drink made with gin. A cousin of the gin fizz, its refreshing and bubbly, impressively loaded with ice in a highball glass. Top with a cocktail cherry and its one of the most sought-after cocktails out there. Every time we serve one to friends, it gets rave reviews. Heres exactly how to make this classic cocktail!',
        },
        {
            name: 'Vesper Martini',
            id: '64',
            image: 'vesper_martini.jpg',
            ingredients:['gin', 'vodka', 'lillet blanc'],
            directions: 'Place the gin, vodka, and Lillet Blanc into a cocktail shaker and fill it with ice. Shake until cold. Strain the drink into a cocktail glass. Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'Heres a cocktail invented by a fictional character that went on to become a classic. Meet the Vesper martini! Yes, James Bond created this drink in the 1953 book Casino Royale, and it lives on today. To us its an improvement on the classic martini, so were glad its stuck around! The magic ingredient is Lillet Blanc, a lightly sweet, vaguely floral fortified wine that brings life and personality into this drink. Heres more about it and why you should try a Bond martini…stat.',
        },
        {
            name: 'White Lady',
            id: '65',
            image: 'white_lady.jpg',
            ingredients:['gin', 'cointreau', 'lemon juice', 'egg white', 'lemon twist'],
            directions: 'Add the gin, Cointreau, lemon juice, and egg white to a cocktail shaker without ice. Shake for 15 seconds. Add the ice to the cocktail shaker. Shake again for 30 seconds. Strain the drink into a martini or cocktail glass; the foam will collect at the top. Serve garnished with a lemon twist or lemon wedge.',
            rating: '9',
            description: 'Heres a smooth, citrus forward classic cocktail with a sophisticated vibe: the White Lady cocktail! This 1920s style sour is clear and crisp, with a refreshing flavor and a frothy egg white foam topping. Its super classy, perfect for a cocktail night or just sipping on the porch. Alex and I have been working our way through great cocktails, and this is one is a standout. (Plus, were huge fans of sour cocktails, so its right up our alley.) Ready to shake it up?',
        },
        {
            name: 'White Negroni',
            id: '66',
            image: 'white_negroni.jpg',
            ingredients:['gin', 'suze', 'lillet blanc', 'lemon peel'],
            directions: 'Combine the gin, Suze and Lillet Blanc in a cocktail mixing glass (or any other type of glass). Fill the mixing glass with 1 handful ice and stir continuously for 30 seconds. Add ice to a lowball glass, and strain the drink into the glass (or you can use a cocktail glass without ice). Use a knife to remove a 1″ wide strip of the lemon peel. Squeeze the lemon peel into the drink to release the oils. Gently run the peel around the edge of the glass, then place it in the glass and serve.',
            rating: '9',
            description: 'Heres a twist on the classic cocktail that every adventurous drinker needs to try: the White Negroni! This lighter spin on a Negroni and has a vibrant, clear yellow color thats unmistakable. And the flavor? Light, a little floral, still bitter, but decidedly more interesting than the classic (in our opinion). It requires a few special ingredients, but theyre absolutely worth adding to your collection. Heres how to make it!',
        },
        // {
        //     name: '',
        //     id: '67',
        //     image: '.jpg',
        //     ingredients:[''],
        //     directions: '',
        //     rating: '9',
        //     description: '',
        // },
        // {
        //     name: '',
        //     id: '68',
        //     image: '.jpg',
        //     ingredients:[''],
        //     directions: '',
        //     rating: '9',
        //     description: '',
        // },
        // {
        //     name: '',
        //     id: '69',
        //     image: '.jpg',
        //     ingredients:[''],
        //     directions: '',
        //     rating: '9',
        //     description: '',
        // },
        // {
        //     name: '',
        //     id: '70',
        //     image: '.jpg',
        //     ingredients:[''],
        //     directions: '',
        //     rating: '9',
        //     description: '',
        // },
    ],
    ingredients: [
    {
        alcohol: [
            {
                wine: [
                    {
                        red: [
                            'cabernet sauvignon',
                            'pinot noir',
                            'red blends',
                            'malbec',
                            'merlot',
                        ],
                        white: [
                            'sauvignon Blanc',
                            'chardonnay',
                            'pinot grigio',
                            'moscato',
                            'riesling',
                            'lillet blanc',
                        ],
                        sparkling: [
                            'champagne',
                            'prosecco',
                            'amercian sparkling',
                            'sparkling rose',
                        ],
                        pink_wine: [
                            'rose',
                            'white zinfadel',
                            'pink moscato',
                        ],
                        dessert_and_fortified: [
                            'port',
                            'dessert wine',
                            'vermouth',
                            'sherry',
                            'madeira',
                            'ice wine / eiswein',
                            'marsala',
                            'pedro zimenez',
                        ]
                    }
                ],
                spirits: [
                    {
                        whiskey: [
                            'bourbon',
                            'scotch whisky',
                            'irish whiskey',
                            'american whiskey',
                            'rye whiskey',
                            'japanese whisky',
                            'canadian whisky',
                            'flavored whiskey',
                        ]
                    },
                    {
                        tequila: [
                            'blanco',
                            'anejo',
                            'reposado tequila',
                            'gold',
                            'flavored',
                        ]
                    },
                    {
                        gin: [
                            'london dry',
                            'modern',
                            'genever / dutch',
                            'aged',
                            'old tom',
                            'navy strength',
                        ]
                    },
                    {
                        general_rum: [
                            'rum',
                            'aged rum',
                            'Flavored Rum',
                            'White Rum',
                            'Spiced Rum',
                            'Gold Rum',
                            'Dark Rum',
                        ]
                    },
                    {
                        brandy: [
                            'cognac',
                            'armagnac',
                            'fruit brandy',
                            'grappa',
                            'flavored brandy',
                            'eau de vie',
                            'calvados',
                            'pisco',
                        ]
                    },
                    {
                        liqueur: [
                            'benedictine',
                            'fruit liqueur',
                            'cream liqueur',
                            'cherry liqueur',
                            'herbal liqueur',
                            'triple sec liqueur',
                            'cointreau',
                            'amaretto liqueur',
                            'other liqueur',
                            'chocolate liqueur',
                            'coffee liqueur',
                            'anise liqueur',
                            'sloe gin',
                            'suze',
                        ]
                    },
                    {
                        other: [
                            'vodka',
                            'mezcal',
                        ]
                    }
                ],
                beer: [
                    'IPA',
                    'hard seltzer',
                    'lager',
                    'light beer',
                    'ale',
                    'stout',
                    'sour beer',
                    'belgian',
                    'cider',
                    'hazy IPA',
                    'non-alcoholic',
                    'ginger beer',
                ]
            }
        ],
        mixers: [
            'lime juice',
            'grenadine',
            'orange juice',
            'lemon juice',
            'orange juice',
            'orange bitters',
            'angostura bitters',
            'pineapple juice',
            'apple juice',
            'simple syrup',
            'pomegranite juice',
            'egg white',
            'orange bitters',
            'cranberry juice',
            'club soda',
            'soda',
            'cream',
            'grapefruit juice',
            'milk',
            'tomato juice',
            'worchestershire sauce',
            'horseradish',
            'hot sauce',
            'tabasco',
            'heavy cream',
            'orange flower water',
        ],
        garnishes: [
            'olives',
            'maraschino cherries',
            'limes',
            'lemons',
            'lemon peel',
            'lemon twist',
            'lemon wedge',
            'rosemary',
            'salt',
            'cinnamon',
            'mint leaves',
            'celery',
            'cocktail onions',
            'cucumbers',
            'oranges',
            'whipped cream',
            'apples',
            'bananas',
            'candy',
            'chocolate',
            'pineapples',
            'strawberries',
            'celery seeds',
            'celery salt',
            'black pepper',
            'old bay seasoning',
            
        ]
    }
]
}

export default newData